name: oceanqast
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - fortran-compiler
  - netcdf-fortran
  - jupyterlab
  - cmake
  - numpy
  - matplotlib=3.4.*
  - scipy
  - ipympl
  - netcdf4
  - pyyaml
  - nco
  - salib
  - blas    # for EAT
  - lapack  # for EAT
  - mpi4py  # for EAT
  - cython  # for EAT
  - pyqt    # for PyNcView
  - R=4.1
  - r-base
  - r-essentials
  - pip:
      - -e ./seamless-notebooks/extern/parsac
      - pyncview
##      - pp (TO DO: solve)
##      - https://www.parallelpython.com/downloads/pp/pp-1.6.4.4.zip
